// Datos de los niveles y sus respectivas pestañas
export const niveles = [
    {
        id: '1',
        nombre: 'Preparatoria Semestral',
        pestañas: [
            { id: 'campus', nombre: 'Campus' },
            { id: 'programas', nombre: 'Planes' },
            { id: 'periodo', nombre: 'Periodo' },
            { id: 'seguros', nombre: 'Seguros' },
            { id: 'becas', nombre: 'Becas' },
            { id: 'apoyos', nombre: 'Apoyos' },
            { id: 'apoyos-fijos', nombre: 'Apoyos Fijos' },
            { id: 'carga-materias', nombre: 'Materias' },
            { id: 'costo-materias', nombre: 'Costos' },
            { id: 'beneficios', nombre: 'Beneficios' },
            { id: 'interes', nombre: 'Interes' },
        ]
    },
    {
        id: '2',
        nombre: 'Profesional Semestral',
        pestañas: [
            { id: 'campus', nombre: 'Campus' },
            { id: 'programas', nombre: 'Planes' },
            { id: 'periodo', nombre: 'Periodo' },
            { id: 'seguros', nombre: 'Seguros' },
            { id: 'becas', nombre: 'Becas' },
            { id: 'apoyos', nombre: 'Apoyos' },
            { id: 'apoyos-fijos', nombre: 'Apoyos Fijos' },
            { id: 'prestamos', nombre: 'Prestamos' },
            { id: 'carga-creditos', nombre: 'Creditos' },
            { id: 'costo-materias', nombre: 'Costos' },
            { id: 'beneficios', nombre: 'Beneficios' },
            { id: 'interes', nombre: 'Interes' },
        ]
    },
    {
        id: '3',
        nombre: 'Preparatoria Tetramestral',
        pestañas: [
            { id: 'campus', nombre: 'Campus' },
            { id: 'programas', nombre: 'Planes' },
            { id: 'periodo', nombre: 'Periodo' },
            { id: 'seguros', nombre: 'Seguros' },
            { id: 'becas', nombre: 'Becas' },
            { id: 'apoyos', nombre: 'Apoyos' },
            { id: 'apoyos-fijos', nombre: 'Apoyos Fijos' },
            { id: 'carga-materias', nombre: 'Materias' },
            { id: 'costo-materias', nombre: 'Costos' },
            { id: 'beneficios', nombre: 'Beneficios' },
            { id: 'interes', nombre: 'Interes' },
        ]
    },
    {
        id: '4',
        nombre: 'Profesional Semestral MAPS',
        pestañas: [
            { id: 'campus', nombre: 'Campus' },
            { id: 'programas', nombre: 'Planes' },
            { id: 'periodo', nombre: 'Periodo' },
            { id: 'certificados', nombre: 'Certificados' },
            { id: 'ingles', nombre: 'Ingles' },
            { id: 'semanas', nombre: 'Semanas' },
            { id: 'seguros', nombre: 'Seguros' },
            { id: 'becas', nombre: 'Becas' },
            { id: 'apoyos', nombre: 'Apoyos' },
            { id: 'apoyos-fijos', nombre: 'Apoyos Fijos' },
            { id: 'prestamos', nombre: 'Prestamos' },
            { id: 'costo-materias', nombre: 'Costos' },
            { id: 'beneficios', nombre: 'Beneficios' },
            { id: 'interes', nombre: 'Interes' },
        ]
    },
    {
        id: '5',
        nombre: 'Pofesional Asociado',
        pestañas: [
            { id: 'campus', nombre: 'Campus' },
            { id: 'programas', nombre: 'Planes' },
            { id: 'formato_asociado', nombre: 'Formato' },
            { id: 'periodo', nombre: 'Periodo' },
            { id: 'seguros', nombre: 'Seguros' },
            { id: 'apoyos', nombre: 'Apoyos' },
            { id: 'apoyos-fijos', nombre: 'Apoyos Fijos' },
            { id: 'prestamos', nombre: 'Prestamos' },
            { id: 'certificados', nombre: 'Certificados' },
            { id: 'beneficios', nombre: 'Beneficios' },
            { id: 'interes', nombre: 'Interes' },
        ]
    },
    {
        id: '6',
        nombre: 'Ejecutivo',
        pestañas: [
            { id: 'campus', nombre: 'Campus' },
            { id: 'programas', nombre: 'Planes' },
            { id: 'formato', nombre: 'Formato' },
            { id: 'periodo', nombre: 'Periodo' },
            { id: 'seguros', nombre: 'Seguros' },
            { id: 'becas', nombre: 'Becas' },
            { id: 'apoyos', nombre: 'Apoyos' },
            { id: 'apoyos-fijos', nombre: 'Apoyos Fijos' },
            { id: 'prestamos', nombre: 'Prestamos' },
            { id: 'carga-creditos', nombre: 'Creditos' },
            { id: 'costo-materias', nombre: 'Costos' },
            { id: 'beneficios', nombre: 'Beneficios' },
            { id: 'interes', nombre: 'Interes' },
        ]
    },
    {
        id: '7',
        nombre: 'Maestria y Especialidades',
        pestañas: [
            { id: 'campus', nombre: 'Campus' },
            { id: 'programas', nombre: 'Planes' },
            { id: 'formato', nombre: 'Formato' },
            { id: 'periodo', nombre: 'Periodo' },
            { id: 'seguros', nombre: 'Seguros' },
            { id: 'becas', nombre: 'Becas' },
            { id: 'apoyos', nombre: 'Apoyos' },
            { id: 'apoyos-fijos', nombre: 'Apoyos Fijos' },
            { id: 'prestamos', nombre: 'Prestamos' },
            { id: 'carga-materias', nombre: 'Materias' },
            { id: 'costo-materias', nombre: 'Costos' },
            { id: 'beneficios', nombre: 'Beneficios' },
            { id: 'interes', nombre: 'Interes' },
        ]
    },
    {
        id: '8',
        nombre: 'Master',
        pestañas: [
            { id: 'campus', nombre: 'Campus' },
            { id: 'programas', nombre: 'Planes' },
            { id: 'formato', nombre: 'Formato' },
            { id: 'periodo', nombre: 'Periodo' },
            { id: 'seguros', nombre: 'Seguros' },
            { id: 'becas', nombre: 'Becas' },
            { id: 'apoyos', nombre: 'Apoyos' },
            { id: 'apoyos-fijos', nombre: 'Apoyos Fijos' },
            { id: 'prestamos', nombre: 'Prestamos' },
            { id: 'certificados', nombre: 'Certificados' },
            { id: 'costo-materias', nombre: 'Costos' },
            { id: 'beneficios', nombre: 'Beneficios' },
            { id: 'interes', nombre: 'Interes' },
        ]
    },
    {
        id: '9',
        nombre: 'MLP Connect',
        pestañas: [
            { id: 'campus', nombre: 'Campus' },
            { id: 'programas', nombre: 'Planes' },
            { id: 'formato', nombre: 'Formato' },
            { id: 'periodo', nombre: 'Periodo' },
            { id: 'seguros', nombre: 'Seguros' },
            { id: 'becas', nombre: 'Becas' },
            { id: 'apoyos', nombre: 'Apoyos' },
            { id: 'apoyos-fijos', nombre: 'Apoyos Fijos' },
            { id: 'certificados', nombre: 'Certificados' },
            { id: 'costo-materias', nombre: 'Costos' },
            { id: 'beneficios', nombre: 'Beneficios' },
            { id: 'interes', nombre: 'Interes' },
        ]
    },
    {
        id: '10',
        nombre: 'MEDU+',
        pestañas: [
            { id: 'campus', nombre: 'Campus' },
            { id: 'programas', nombre: 'Planes' },
            { id: 'formato', nombre: 'Formato' },
            { id: 'periodo', nombre: 'Periodo' },
            { id: 'seguros', nombre: 'Seguros' },
            { id: 'becas', nombre: 'Becas' },
            { id: 'apoyos', nombre: 'Apoyos' },
            { id: 'apoyos-fijos', nombre: 'Apoyos Fijos' },
            { id: 'carga-creditos', nombre: 'Creditos' },
            { id: 'costo-materias', nombre: 'Costos' },
            { id: 'beneficios', nombre: 'Beneficios' },
            { id: 'interes', nombre: 'Interes' },
        ]
    },
    {
        id: '11',
        nombre: 'MLP Presencial',
        pestañas: [
            { id: 'campus', nombre: 'Campus' },
            { id: 'programas', nombre: 'Planes' },
            { id: 'formato', nombre: 'Formato' },
            { id: 'periodo', nombre: 'Periodo' },
            { id: 'seguros', nombre: 'Seguros' },
            { id: 'becas', nombre: 'Becas' },
            { id: 'apoyos', nombre: 'Apoyos' },
            { id: 'apoyos-fijos', nombre: 'Apoyos Fijos' },
            { id: 'carga-materias', nombre: 'Materias' },
            { id: 'costo-materias', nombre: 'Costos' },
            { id: 'beneficios', nombre: 'Beneficios' },
            { id: 'interes', nombre: 'Interes' },
        ]
    },
    {
        id: '12',
        nombre: 'Connect Presencial Matutino',
        pestañas: [
            { id: 'campus', nombre: 'Campus' },
            { id: 'programas', nombre: 'Planes' },
            { id: 'formato', nombre: 'Formato' },
            { id: 'periodo', nombre: 'Periodo' },
            { id: 'seguros', nombre: 'Seguros' },
            { id: 'becas', nombre: 'Becas' },
            { id: 'apoyos', nombre: 'Apoyos' },
            { id: 'apoyos-fijos', nombre: 'Apoyos Fijos' },
            { id: 'carga-materias', nombre: 'Materias' },
            { id: 'costo-materias', nombre: 'Costos' },
            { id: 'beneficios', nombre: 'Beneficios' },
            { id: 'interes', nombre: 'Interes' },
        ]
    },
    {
        id: '13',
        nombre: 'Ejecutivo Bimestral MAPS',
        pestañas: [
            { id: 'campus', nombre: 'Campus' },
            { id: 'programas', nombre: 'Planes' },
            { id: 'formato', nombre: 'Formato' },
            { id: 'seguros', nombre: 'Seguros' },
            { id: 'becas', nombre: 'Becas' },
            { id: 'apoyos', nombre: 'Apoyos' },
            { id: 'apoyos-fijos', nombre: 'Apoyos Fijos' },
            { id: 'prestamos', nombre: 'Prestamos' },
            { id: 'beneficios', nombre: 'Beneficios' },
            { id: 'semanas', nombre: 'Semanas' },
            { id: 'certificados', nombre: 'Certificados' },
            { id: 'costo-materias', nombre: 'Costos' },
            { id: 'pagos-bimestrales', nombre: 'Pagos Bimestrales' }
        ]
    },
    {
        // Nivel bimestral MAPS de posgrado. Colegiatura = certificados × $14,990 (1 crédito/cert).
        // Apoyos: Becas, Apoyo estudiantil en $ y en %, y Préstamo. No aplica: seguros ni semana SEDI.
        id: '15',
        nombre: 'Posgrados MAPS',
        pestañas: [
            { id: 'campus', nombre: 'Campus' },
            { id: 'programas', nombre: 'Planes' },
            { id: 'formato', nombre: 'Formato' },
            { id: 'becas', nombre: 'Becas' },
            { id: 'apoyos', nombre: 'Apoyos' },
            { id: 'apoyos-fijos', nombre: 'Apoyos Fijos' },
            { id: 'prestamos', nombre: 'Prestamos' },
            { id: 'beneficios', nombre: 'Beneficios' },
            { id: 'certificados', nombre: 'Certificados' },
            { id: 'costo-materias', nombre: 'Costos' },
            { id: 'pagos-bimestrales', nombre: 'Pagos Bimestrales' }
        ]
    },
];